# Generated by Django 4.1.5 on 2023-02-22 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_medicament_patient_balance_visit_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='time',
        ),
        migrations.AddField(
            model_name='appointment',
            name='available_slot',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='available_slot', to='api.availableslot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='health_card_number',
            field=models.CharField(default='1111111121', max_length=13, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.CharField(default='avatar1.jpg', max_length=50),
        ),
    ]
