# Generated by Django 4.1.5 on 2023-02-27 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_appointment_date_remove_appointment_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
    ]
